/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?




Answer: 76576500
*/

import java.util.*;
import java.math.BigInteger;



public class HiDivTri{

    public static void main(String[] args){

int i = 1;
int tri = 1;
        while(true){
          i++;

          tri += i;


          if(numberOfDivisors(tri) > 500){

                System.out.println( tri );
                break;

          }


        }





    }


      static long numberOfDivisors(long num){
            BigInteger number;
            number = BigInteger.valueOf(num);

            BigInteger x = BigInteger.valueOf(2);
            long totalFactors = 1;


            while (x.multiply(x).compareTo(number) <= 0) {
                    int power = 0;
                      while (number.mod(x).equals(BigInteger.ZERO)) {
                        power++;
                        number = number.divide(x);
                      }

          totalFactors *= (power + 1);
          x = x.add(BigInteger.ONE);

         }

          if (!number.equals(BigInteger.ONE)) {
              totalFactors *= 2;
            }


            return totalFactors;


         }
}
