/*

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?


Answer: 5482660
*/


// How to I Prove it is smallest ?

public class PentSumDif{


    static public void main(String[] args){

      int max = 100000;
      int penti=0;
      int pentj=0;

      int smallest = Integer.MAX_VALUE;
      int pent1=0;
      int pent2=0;


        for(int i = 1; i <= max ;i++){
        penti = i* ((3*i) - 1)/2;
                for(int j = 1; j <= max  ;j++){
                pentj = j*(( 3 * j ) - 1)/2;

                      if( isPent(penti+pentj)  &&  isPent(Math.abs(penti - pentj))   ){

                          if(Math.abs(penti-pentj) < smallest  ){
                            smallest = Math.abs(penti-pentj);
                             System.out.println( smallest );
                          }

                      }

                }
        }





    }



          public static boolean isPent(long x) {

            return Math.sqrt(1+24*x) % 6 == 5;

           }


}
